apiVersion: apps/v1
kind: Deployment
metadata:
  name: petrosa-crypto-candles-consistency-checker
  namespace: petrosa-apps
  labels:
    app: petrosa-crypto-candles-consistency-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petrosa-crypto-candles-consistency-checker
  template:
    metadata:
      labels:
        app: petrosa-crypto-candles-consistency-checker
    spec:
      containers:
      - name: petrosa-crypto-candles-consistency-checker
        image: yurisa2/petrosa-crypto-candles-consistency-checker:v0.0.83
        imagePullPolicy: Always
        env:
          - name: OTEL_SERVICE_NAME
            value: "petrosa-crypto-candles-consistency-checker"
          - name: VERSION
            value: "v0.0.83"
          - name: MARKET
            value: "crypto"
        envFrom:
          - configMapRef:
              name: petrosa-apps-configmap
      restartPolicy: Always
